### ISSUE TITLE
Webpage

### ISSUE THREAD

**Issue by Ash258** [rasa/scoop-directory#1]
Is there any plan to convert this project into some 🔥 webpage?? (like [choco](https://chocolatey.org/packages), [homebrew](https://formulae.brew.sh/formula/))
Webpage with all buckets, manifests, some search field, links, periodically updated, ... 🤔 

It would help new users to discover Scoop.

API for searching would be 💯 too and much faster than current `scoop search`.

**Comment by rasa** [comment]
All great ideas. I would love to do that, but am time-constrained for the next few months.

**Comment by rasa** [comment]
Search added in #60.
