### ISSUE TITLE
Is there any way to install Jenkins?

### ISSUE THREAD

**Issue by kid1412621** [rasa/scoop-directory#10]

**Comment by rasa** [comment]
No sure I follow. Can you elaborate?

**Comment by kid1412621** [comment]
I cannot find Jenkins(the CI tool) in scoop repo or any scoop bucket.

**Comment by tech189** [comment]
Have you tried searching here? https://scoop.netlify.com/apps/
I found jcli and jx by searching 'jenkins' - not sure if those are what you need

**Comment by rashil2000** [comment]
> Have you tried searching here? https://scoop.netlify.com/apps/ I found jcli and jx by searching 'jenkins' - not sure if those are what you need

That search index is very outdated. You can use this repo's own search index for finding packages - https://rasa.github.io/scoop-directory/search
