### ISSUE TITLE
Small problem with generated documents: [clash](https: //github.com/Fndroid/clash_for_windows_pkg)

### ISSUE THREAD

**Issue by zhoujin7** [rasa/scoop-directory#18]
bucket:
AStupidBear/scoop-bear

`[clash](https: //github.com/Fndroid/clash_for_windows_pkg)  [0.7.6](https: //github.com/Fndroid/clash_for_windows_pkg)`

![aaaaa](https://user-images.githubusercontent.com/8288988/68870194-76710180-0735-11ea-93f5-08a4cf0843f4.png)

**Comment by zhoujin7** [comment]
These apps don't have version info.
KMS				https://github.com/Ash258/scoop-Ash258
hello				https://github.com/MattKang/scoop-bucket
llvm				https://github.com/TheCjw/scoop-retools
syncthing				https://github.com/dennislloydjr/scoop-bucket-devbox
schema				https://github.com/michaelxmcbride/scoop-michaelxmcbride

**Comment by rasa** [comment]
Fixed in https://github.com/AStupidBear/scoop-bear/pull/2
