### ISSUE TITLE
Generate a sqlite3 db file?

### ISSUE THREAD

**Issue by zhoujin7** [rasa/scoop-directory#19]
```sql
PRAGMA foreign_keys = false;

DROP TABLE IF EXISTS "app";
CREATE TABLE "app" (
  "id" INTEGER,
  "name" TEXT,
  "version" TEXT,
  "description" TEXT,
  "license" TEXT,
  "bucket_repo" TEXT
);

DROP TABLE IF EXISTS "bucket";
CREATE TABLE "bucket" (
  "score" real,
  "bucket_repo" TEXT NOT NULL,
  "apps" integer,
  "stars" integer,
  "forks" integer,
  "updated" text,
  PRIMARY KEY ("bucket_repo")
);

PRAGMA foreign_keys = true;
```
Maybe need add more table fields.

**Comment by zhoujin7** [comment]
It can be easy search some info of scoop buckets with some code once generated a sqlite3 db file.

**Comment by zhoujin7** [comment]
The command `scoop search app` can only search app that in added buckets. I want to write a cmdlet search all possible apps even it not in buckets that is added.

**Comment by zhoujin7** [comment]
find-scoopApp.ps1
```powershell
param(
    [Parameter(Mandatory = $true)][string]$appName
)

$body = ConvertTo-Json @{ app_name = $appName }
$uri = 'http://scoop.zhoujin7.com:8080/search'
$response = Invoke-RestMethod -URI $uri -Method Post -ContentType 'application/json' -Body $body
Write-Output $response
```
Usage:
![image](https://user-images.githubusercontent.com/8288988/69028773-02bd4600-0a0e-11ea-84fe-b24a83bdf517.png)

**Comment by zhoujin7** [comment]
https://github.com/zhoujin7/crawl-scoop-directory

**Comment by zhoujin7** [comment]
I write a simple web api that can be used in query all possible apps.
https://github.com/zhoujin7/scoop-search

Python Flask and php
https://github.com/zhoujin7/scoop-search/blob/master/app.py
https://github.com/zhoujin7/scoop-search/blob/master/search.php

Query client:
https://github.com/zhoujin7/scoop-search/blob/master/scoopSearch.ps1
![image](https://user-images.githubusercontent.com/8288988/70504694-3dc01e80-1b61-11ea-86fe-88a5d8d58d8c.png)

I have deployed the program to my cloud server, but the query speed may be slow, even timeout.
🤷‍♂️

**Comment by rashil2000** [comment]
Hi @zhoujin7 
This is a very nice thing! However, while your database updates daily, your query client doesn't seem to be up to date. I have created an issue for it in your repo zhoujin7/scoop-search#2
I created this simple PowerShell function that provides search functionality locally through the commandline, and uses (and updates itself) your SQLite database file.

```powershell
param(
  [String]$Name,
  [String]$Description,
  [String]$Version,
  [String]$Bucket_Repo,
  [String]$Table = 'app',
  [Switch]$ForceUpdate = $false
)

$DBFile = 'D:\Data\Projects\Random\scoop_directory.db'

if ($Table -eq 'bucket') {
  if (!($Bucket_Repo)) {
    Write-Host "`nEnter bucket repository query.`n" -ForegroundColor Red
    return
  }
  $query = "SELECT bucket_repo,apps,updated,stars FROM bucket WHERE bucket_repo LIKE `"%$Bucket_Repo%`" ORDER BY apps DESC;"
} else {
  if (!($Name -or $Description)) {
    Write-Host "`nEnter at least one of name or description.`n" -ForegroundColor Red
    return
  }
  $query = "SELECT name,version,bucket_repo,description FROM app WHERE name LIKE `"%$Name%`" AND description LIKE `"%$Description%`" AND version LIKE `"%$Version%`" AND bucket_repo LIKE `"%$Bucket_Repo%`" ORDER BY version DESC;"
}

if (!(Test-Path $DBFile) -or ((Get-Date) - (Get-Item $DBFile).LastWriteTime).TotalHours -ge 24 -or $ForceUpdate) {
  Invoke-WebRequest 'https://raw.githubusercontent.com/zhoujin7/crawl-scoop-directory/master/scoop_directory.db' -UseBasicParsing -OutFile $DBFile
  Write-Host "`nUpdated database - $DBFile.`n" -ForegroundColor Green
}

return Invoke-SqliteQuery -Database $DBFile -Query $query
```

(Run `Install-Module PSSQLite` before using this.)
