### ISSUE TITLE
Output markdown files are no longer viewable on Github

### ISSUE THREAD

**Issue by littleli** [rasa/scoop-directory#25]
I spotted generated output files are large enougth so that Github only allows you to download them as raw files. It's quite annoying. Solution can be to publish files to Github pages or shrink the output files enough so they're viewable again.

**Comment by rasa** [comment]
@littleli Thanks for the report. Dropping from 20 to 15 fixed it (for now!)

**Comment by rasa** [comment]
@littleli I published to Github pages, so that should avoid this issue in the future. Thanks for the suggestion!
