### ISSUE TITLE
.md files have grown too big for github to display.

### ISSUE THREAD

**Issue by MCOfficer** [rasa/scoop-directory#5]
Title pretty much says it all. Upon clicking one of the links in the README, i'm greeted with this:
![firefox_2018-12-15_01-33-01](https://user-images.githubusercontent.com/22377202/50036488-79d1a980-0009-11e9-86b8-41bb50d3f0e0.png)

the only option to view the content without downloading it is to have a markdown viewer extension installed, which is probably not desirable.

**Comment by rasa** [comment]
Yeah, I just changed max_pages to 3 in 
https://github.com/rasa/scoop-directory/commit/cba11c7ddbc68047dd7f310aa04ecc3a5766c4c7
If that doesn’t fix it, I will try 2 and then 1.

**Comment by MCOfficer** [comment]
after waiting for it to update (and forgetting about it for a few days): yes, that looks good.
