### ISSUE TITLE
Versions are not up to date

### ISSUE THREAD

**Issue by rashil2000** [rasa/scoop-directory#54]
See notepadplusplus for example - it is on 8.1 in both extras and nonportable bucket, but on your website it is still showing 7.9.5.

I see that the repo has a last commit 11 days ago. Did Travis CI fail or something?

**Comment by rasa** [comment]
@rashil2000 Fixed now. Thanks for the heads up. Since June 15th, 2021, the building on travis-ci.org is ceased. I had to move it to use travis-ci.com .

**Comment by rasa** [comment]
travis-ci.com is now asking for money. That's a go-based action. This repo is python.

**Comment by rashil2000** [comment]
There are python-based GitHub Actions too - https://github.com/actions/setup-python

I was just giving an example of a repo that works similarly to scoop-directory (i.e. updates daily).
