### ISSUE TITLE
Can't shim possibly because it couldn't create the linked current folder

### ISSUE THREAD

**Issue by asaph96** [rasa/scoop-directory#57]
When I started a new scoop installation, I've run into the problem that no matter what program I try to install, scoop is not able to create the shim:

    scoop install git
    Installing '7zip' (19.00) [64bit]
    7z1900-x64.msi (1,7 MB) 
    [===================================================================] 100%
    Checking hash of 7z1900-x64.msi ... ok.
    Extracting 7z1900-x64.msi ... done.
    Linking E:\Programs\Scoop\apps\7zip\current => E:\Programs\Scoop\apps\7zip\19.00
    Creating shim for '7z'.
    Can't shim '7z.exe': File doesn't exist.

I've tried to install it in another directory, but it doesn't seem to help.

When I dig into the apps directory, the 7zip dir doesn't contain the `current` link folder:
![image](https://user-images.githubusercontent.com/20308482/136085078-6325f85c-7d72-4683-936d-b524f16fb384.png)
but during the installation, it passed the Linking step without raising an error.

Since I can't even install 7zip, let alone git, I can't update scoop, nor install anything, as it continues to exhibit the same behavior.

**Comment by rashil2000** [comment]
This issue is not relevant here. Try searching the open issues on https://github.com/ScoopInstaller/Scoop

**Comment by rasa** [comment]
Yes, please create this issue at https://github.com/ScoopInstaller/Scoop .
