### ISSUE TITLE
https://rasa.github.io/scoop-directory/by-score  Page404

### ISSUE THREAD

**Issue by diklios5768** [rasa/scoop-directory#64]

**Comment by diklios5768** [comment]
The GitHub score page 404

**Comment by rasa** [comment]
I removed it, as it's been deprecated for months. Please use another of the pages.

**Comment by rasa** [comment]
See https://github.com/rasa/scoop-directory/commit/69e0c20b56d5f67c2876dcee9ea8db81c6a0576d#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L37

**Comment by diklios5768** [comment]
> See [69e0c20#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L37](https://github.com/rasa/scoop-directory/commit/69e0c20b56d5f67c2876dcee9ea8db81c6a0576d#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L37)

OK, when the page was removed, the README.md has not been updated. So, I don't know.

I often use this page to search some software because it shows all of them by score and I can search them even in description (I know the search page can search description just now Ｏ(≧口≦)Ｏ).
Shovel only include part of software. And https://rasa.github.io/scoop-directory/search somethings return nothing because of network (but I don't know if it is my network error because of not know 'Query 10599 manifests among 389 buckets' is the hint, it is just too small).

Thanks.

**Comment by rasa** [comment]
I added the by-score.md page back, but it’s used linked to in the readme any more, so it should be migrated away from eventually.
