### ISSUE TITLE
Another Search service

### ISSUE THREAD

**Issue by rashil2000** [rasa/scoop-directory#65]
In the "Other tools" section, this awesome service seems to be a worthy addition.

https://scoopsearch.github.io

It has 3 repos in the org called https://github.com/ScoopSearch and uses Azure to power the search. 

I got to know about it from here https://github.com/kidonng/scoop-docs/issues/40#issuecomment-784028242

> I wrote a scoop packages search engine a couple of months ago: https://scoopsearch.github.io. I got inspiration from the Chocolatey website to try to "showcase" the packages (icons, certified buckets, repositories stars...)
> 
> Four times a day, the backend crawls GitHub for repositories containing keywords "scoop-bucket", parses manifests and updates results in an Azure search service.
> 
> (source for backend and frontend is available on: https://github.com/ScoopSearch)

**Comment by rasa** [comment]
Yikes! This sucker kicks our ass. Good find.

**Comment by rashil2000** [comment]
Ikr!

The only issue is it doesn't filter out forks of buckets yet (and doesn't have exceptions). So the results are sometimes duplicated. 

But otherwise the UX is really good, and it even has little checkbox to tell if a bucket is well-known :)

**Comment by rasa** [comment]
Updated readme
