### ISSUE TITLE
Start search from url (e.g. ?q="asdf")

### ISSUE THREAD

**Issue by tech189** [rasa/scoop-directory#77]
It would be nice to be able to start a search straight from the URL bar with an argument in the URL like a search engine. For example like Chocolatey's package search: `https://community.chocolatey.org/packages?q=asdf`. We could have `https://rasa.github.io/scoop-directory/search?q=asdf` Then you could set up a search shortcut/bookmark in your browser using the `%s` substitute marker (not sure what it's called), so you just have to type `scoop asdf` to start your search! 😄

**Comment by rasa** [comment]
Yeah. I tried to get that working via
https://github.com/rasa/scoop-directory/blob/5a7b893254325a40f69e6b2ca80ac8249277466f/search.html#L159-L163 , but it didn't work. Perhaps @rashil2000 has a solution?
