### ISSUE TITLE
(Sorry about that, but we can’t show files that are this big right now.)

### ISSUE THREAD

**Issue by linsui** [rasa/scoop-directory#9]
The markdown is too big to display again...

**Comment by rasa** [comment]
I guess we need to only display the first 100 matches, or implement pagination. The former is a quick fix.

**Comment by linsui** [comment]
Maybe we can show a table of contents and put every bucket in different markdown?

**Comment by BjornSigurd** [comment]
Please fix!!!  I have a C# file holding 23.000.  I really think GitHub should be able to handle it!!

**Comment by ayyappan-dot** [comment]
please

**Comment by rasa** [comment]
@ayyappan-dot Use the links on https://rasa.github.io/scoop-directory/
